version: '2'
services:
  
  kong:
    image: kong:0.14
    restart: always
    depends_on:
      - postgres
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DB=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    command: sh -c "echo 'migrating' && kong migrations up && echo 'starting' && kong start"
    ports:
      - "8000:8000"
      - "8001:8001"

  postgres:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    ports:
      - "5432:5432"
networks:
  default:
    external:
      name: kong-net
